import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Minimal Firebase options shim.
///
/// Your `lib/main.dart` expects `DefaultFirebaseOptions.currentPlatform`.
/// In the original FlutterFire flow this file is generated by:
///   `flutterfire configure`
///
/// This version keeps the app compiling even if the file wasn't generated.
/// It reads options from `--dart-define` keys and throws a descriptive error
/// when required values are missing.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        throw UnsupportedError('FirebaseOptions are not supported for Fuchsia.');
    }
  }

  static FirebaseOptions get android {
    const apiKey = String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
    const appId = String.fromEnvironment('FIREBASE_ANDROID_APP_ID');
    const messagingSenderId = String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
    const projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
    const storageBucket = String.fromEnvironment('FIREBASE_STORAGE_BUCKET');

    _requireConfigured(
      platformName: 'Android',
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      requiredKeys: const [
        'FIREBASE_ANDROID_API_KEY',
        'FIREBASE_ANDROID_APP_ID',
        'FIREBASE_MESSAGING_SENDER_ID',
        'FIREBASE_PROJECT_ID',
      ],
    );

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket.isEmpty ? null : storageBucket,
    );
  }

  static FirebaseOptions get ios {
    const apiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');
    const appId = String.fromEnvironment('FIREBASE_IOS_APP_ID');
    const messagingSenderId = String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
    const projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
    const storageBucket = String.fromEnvironment('FIREBASE_STORAGE_BUCKET');

    _requireConfigured(
      platformName: 'iOS',
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      requiredKeys: const [
        'FIREBASE_IOS_API_KEY',
        'FIREBASE_IOS_APP_ID',
        'FIREBASE_MESSAGING_SENDER_ID',
        'FIREBASE_PROJECT_ID',
      ],
    );

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket.isEmpty ? null : storageBucket,
    );
  }

  static FirebaseOptions get web {
    const apiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
    const appId = String.fromEnvironment('FIREBASE_WEB_APP_ID');
    const messagingSenderId = String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
    const projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
    const authDomain = String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN');
    const storageBucket = String.fromEnvironment('FIREBASE_STORAGE_BUCKET');
    const measurementId = String.fromEnvironment('FIREBASE_WEB_MEASUREMENT_ID');

    _requireConfigured(
      platformName: 'Web',
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      requiredKeys: const [
        'FIREBASE_WEB_API_KEY',
        'FIREBASE_WEB_APP_ID',
        'FIREBASE_MESSAGING_SENDER_ID',
        'FIREBASE_PROJECT_ID',
        'FIREBASE_WEB_AUTH_DOMAIN',
      ],
    );

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain.isEmpty ? null : authDomain,
      storageBucket: storageBucket.isEmpty ? null : storageBucket,
      measurementId: measurementId.isEmpty ? null : measurementId,
    );
  }

  static FirebaseOptions get macos =>
      throw UnsupportedError(_missingGeneratedOptionsMessage('macOS'));

  static FirebaseOptions get windows =>
      throw UnsupportedError(_missingGeneratedOptionsMessage('Windows'));

  static FirebaseOptions get linux =>
      throw UnsupportedError(_missingGeneratedOptionsMessage('Linux'));
}

void _requireConfigured({
  required String platformName,
  required String apiKey,
  required String appId,
  required String messagingSenderId,
  required String projectId,
  required List<String> requiredKeys,
}) {
  if (apiKey.isNotEmpty &&
      appId.isNotEmpty &&
      messagingSenderId.isNotEmpty &&
      projectId.isNotEmpty) {
    return;
  }

  throw UnsupportedError(
    'Firebase is not configured for $platformName.\n'
    'Missing one or more required build-time defines: ${requiredKeys.join(', ')}\n\n'
    'Fix options (choose one):\n'
    '1) Generate the real file using FlutterFire: flutterfire configure\n'
    '2) Provide values via --dart-define when running/building. Example (Android):\n'
    '   flutter run '
    '--dart-define=FIREBASE_ANDROID_API_KEY=... '
    '--dart-define=FIREBASE_ANDROID_APP_ID=... '
    '--dart-define=FIREBASE_MESSAGING_SENDER_ID=... '
    '--dart-define=FIREBASE_PROJECT_ID=...\n\n'
    'Note: Your app currently catches Firebase init errors and will continue running, '
    'but push notifications and other Firebase features will be disabled until configured.',
  );
}

String _missingGeneratedOptionsMessage(String platformName) {
  return 'FirebaseOptions for $platformName are not configured in this repo.\n'
      'Run `flutterfire configure` to generate platform-specific options, '
      'or update `lib/firebase_options.dart` accordingly.';
}
