// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.generated.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLjV0vwF0Ah46l7lvMKcAs2z0dUh94lc',
    appId: '1:776552618546:web:e44e915c66d14df90e3a2b',
    messagingSenderId: '776552618546',
    projectId: 'medaichain-19e32',
    authDomain: 'medaichain-19e32.firebaseapp.com',
    storageBucket: 'medaichain-19e32.firebasestorage.app',
    measurementId: 'G-2E17DGH0WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpSrkoH1xWHaN-7-A5RKe4sp-Sqnz6Pf8',
    appId: '1:776552618546:android:74afa5bf94aac0d80e3a2b',
    messagingSenderId: '776552618546',
    projectId: 'medaichain-19e32',
    storageBucket: 'medaichain-19e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UG1vf4l5_GRGlsk_NA2fgrzbV9TGnjo',
    appId: '1:776552618546:ios:e979a135b7a8b9ac0e3a2b',
    messagingSenderId: '776552618546',
    projectId: 'medaichain-19e32',
    storageBucket: 'medaichain-19e32.firebasestorage.app',
    iosBundleId: 'com.example.madaichain',
  );
}